### ISSUE TITLE
量子RPG报错

### ISSUE THREAD

**Issue by nanchen11** [catserver-3-0/CatServerRepo#23]
请如实填写以下信息 否则不予以处理

服务端版本(/version指令获取):
[19:59:35] [Server thread/INFO]: This server is running CatServer version git-1.12.2-9f7b76c8 (MC: 1.12.2) (Implementing API versi
on 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2838)

Java版本(打开cmd 输入java -version):
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
PS C:\Users\Administrator>

操作系统(Linux/Windows, 请指定详细发行版本):
Windows Server 2012 R2 Standard
2013 Microsoft Corporation

插件列表(/plugins指令):
[20:05:31] [Server thread/INFO]: Plugins (77): ItemDurability, ZombieNoBurn, PlaceholderAPI, GroupManager, MythicLib, PlugMan, ASK
iller, SkillAPIHook, DailyReward, WorldCommandBlock, GuoItemLoreCommand, BanItem, WuXia, CNPCE, FancyCropTrample, MXBukkitLib, Dru
gs, WorldEdit, Forge, Watcher, TabletAPI, AgarthaLib, CrackShot, WorldBorder, KiteBoard, LaggRemover, ProtocolLib, NoRename, MCCor
e, levelgift, AutoRespawnPlus, LeveledItem, LevelChat, Vexhorn, Mcrmb, Vault, VexRecharge, Lores, ClawVIP, CrazyCrates, GPS, Never
Lag, PlotSquared, HolographicDisplays, PlayerPoints, WorldGuard, MyItems, CustomGo, SkillAPI, EasyKitsRel, ChestCommands, RPGInven
tory, Companions, Essentials, ColorMOTD, NoPluginStealers, BountyHunters, Multiverse-Core, TreasureChest, Residence, EssentialsCha
t, RenameCard-Rel, AncientGates, ScriptBlockPlus, BlockParticles, FPSHelper, PhatLoots, EssentialsSpawn, TradeMe, AuthMe, MythicMo
bs, QuantumRPG, VexView, VexAutoMessage, iTeam, VexKeyBoardHelper, VexRPG-Shop

相关mod(全称):
【各种物品】VariedCommodities_1.12.2(29oct17)
Armourers-Workshop-1.12.2-0.49.1
CustomMC-1.12.2
lycanitesmobs
nashorn
动物单车AnimalBikes_1.12.2(13Jan19)
小动物betteranimalsplus-5.0.1
自定义机器人CustomNPCs_1.12.2(30Jan19)(3)

报错日志链接(paste.ubuntu.com): 

https://paste.ubuntu.com/p/BKYrQFKKhR/ 量子RPG报错

**Comment by Luohuayu** [comment]
请使用最新版再反馈

**Comment by nanchen11** [comment]
[21:57:59] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to QuantumRPG v4.0.7.100-BETA
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:69) ~[EventExecutor$2.class:git-1.12.2-9f7b76c8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-1.12.2-9f7b76
c8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [SimplePluginManager.class:git-1.12.2-9f7
b76c8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [SimplePluginManager.class:git-1.12.2-9f7
b76c8]
        at net.minecraft.server.management.PlayerList.playerLoggedIn(PlayerList.java:475) [pl.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:249) [pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:2
55) [NetworkDispatcher.class:git-1.12.2-9f7b76c8]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatc
her.class:git-1.12.2-9f7b76c8]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDi
spatcher$1.class:git-1.12.2-9f7b76c8]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235) [gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:187) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:934) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: Could not resolve method for [ResolverQuery{name='sendPack
et', types=[]}] in class class net.minecraft.network.NetHandlerPlayServer
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.sendPacket(GlowAPI.java:420) ~[?:?]
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.sendTeamPacket(GlowAPI.java:401) ~[?:?]
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.initTeam(GlowAPI.java:325) ~[?:?]
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.initTeam(GlowAPI.java:335) ~[?:?]
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.onJoin(GlowAPI.java:541) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor1007.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-1.12.2-9f7b76c8]
        ... 15 more
Caused by: java.lang.NoSuchMethodException: Could not resolve method for [ResolverQuery{name='sendPacket', types=[]}] in class cla
ss net.minecraft.network.NetHandlerPlayServer
        at su.nightexpress.quantumrpg.libs.reflection.resolver.MethodResolver.notFoundException(MethodResolver.java:118) ~[?:?]
        at su.nightexpress.quantumrpg.libs.reflection.resolver.MethodResolver.notFoundException(MethodResolver.java:1) ~[?:?]
        at su.nightexpress.quantumrpg.libs.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:60) ~[?:?]
        at su.nightexpress.quantumrpg.libs.reflection.resolver.MethodResolver.resolve(MethodResolver.java:100) ~[?:?]
        at su.nightexpress.quantumrpg.libs.reflection.resolver.MethodResolver.resolve(MethodResolver.java:94) ~[?:?]
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.sendPacket(GlowAPI.java:418) ~[?:?]
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.sendTeamPacket(GlowAPI.java:401) ~[?:?]
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.initTeam(GlowAPI.java:325) ~[?:?]
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.initTeam(GlowAPI.java:335) ~[?:?]
        at su.nightexpress.quantumrpg.libs.glowapi.GlowAPI.onJoin(GlowAPI.java:541) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor1007.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-1.12.2-9f7b76c8]
        ... 15 more

**Comment by nanchen11** [comment]
最新版和这个版本都是这个样子
